name: build

on:
  workflow_dispatch:

jobs:
  build-x64-gcc:
    runs-on: windows-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up MSYS2 (MINGW64)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel mingw-w64-x86_64-toolchain
    - name: Build EXE
      run: |
        cd MessageBoxEXE/
        make clean
        make exe
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: EXE
        path: MessageBoxEXE/Bin/MessageBox_x64.exe
        retention-days: 7